"""Added reviewed column to Feedback table

Revision ID: c5456832436b
Revises: 
Create Date: 2025-04-02 20:18:37.685988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5456832436b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('accType',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('Student', 'Instructor', name='accTypeEnum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('accType',
               existing_type=sa.Enum('Student', 'Instructor', name='accTypeEnum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_column('reviewed')

    # ### end Alembic commands ###
